arch: 
    - ppc64le
    - amd64
language: python

sudo: false

install:
    pip install tox

script: tox

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: required  # needed for 3.7
    - python: 2.7
      env: TOXENV=py27 REQUESTS_VERSION="===2.2.1"
    - python: 3.4
      env: TOXENV=py34 REQUESTS_VERSION="===2.2.1"
    - python: 3.5
      env: TOXENV=py35 REQUESTS_VERSION="===2.2.1"
    - python: 3.6
      env: TOXENV=py36 REQUESTS_VERSION="===2.2.1"
    - python: 3.7
      env: TOXENV=py37 REQUESTS_VERSION="===2.2.1"
      dist: xenial
      sudo: required
    - python: pypy
      env: TOXENV=pypy REQUESTS_VERSION="===2.2.1"
    - env: TOXENV=py27-flake8
    - env: TOXENV=py37-flake8
      python: 3.7
      dist: xenial
      sudo: required
    - env: TOXENV=docstrings
    - env: TOXENV=docs
    - env: TOXENV=readme
